import type { Metadata } from "next";
import {
  GaeaBackground,
  GaeaSiteFooter,
  GaeaSiteHeader,
} from "../components/gaea-site-chrome";
import { GaeaSubpageManifesto } from "../components/gaea-subpage-manifesto";
import { LocalizedLink } from "../components/localized-link";
import { settlementDemoCatalog } from "../lib/generated/settlement-demo.generated";
import {
  getLocaleFromSearchParams,
  type Locale,
  type SearchParamsLike,
} from "../lib/i18n";

export const metadata: Metadata = {
  title: "Simulation",
  description:
    "XENOr simulation proof: a deterministic settlement economy slice rendered from real Rust engine output.",
};

const sharedCopy = {
  manifesto: {
    kicker: "Vertical Slice Proof",
    title: ["A real settlement run,", "real artifacts,", "and a public page."],
    summary:
      "This page is fed by a deterministic Rust run from xenor-engine. The slice is intentionally small: workers, food, wood, per-tick production, per-tick consumption, shortages, replay, snapshots, and fixture verification all flow into one readable surface.",
    meta: [
      "settlement economy",
      "deterministic replay",
      "snapshot resume",
      "site-consumed output",
    ],
    actions: {
      primary: "Review repositories",
      secondary: "Open xenor-engine",
    },
    aside: {
      kicker: "What This Proves",
      rows: [
        {
          id: "01",
          title: "Domain logic is real",
          detail:
            "The stack is no longer demonstrating only a sample counter. Worker allocation changes food and wood outcomes in a way that is visible and testable.",
        },
        {
          id: "02",
          title: "Artifacts are usable",
          detail:
            "Replay, snapshot, scenario, and fixture contracts are generated from the same run that drives this page.",
        },
        {
          id: "03",
          title: "The public surface is connected",
          detail:
            "xenor-site is reading exported simulation output instead of restating architecture in the abstract.",
        },
      ],
    },
  },
  summary: {
    kicker: "Run Register",
    title: "The page is backed by one generated catalog from the settlement slice.",
    body:
      "Every row below comes from the deterministic Rust catalog generated by the simulation demo example. Seeds and digests are rendered as strings to preserve exact values across the site boundary.",
    stats: [
      {
        label: "Engine family",
        value: settlementDemoCatalog.engineFamily,
      },
      {
        label: "Scenarios",
        value: String(settlementDemoCatalog.scenarioCount),
      },
      {
        label: "Ticks rendered",
        value: String(
          settlementDemoCatalog.scenarios.reduce(
            (total, scenario) => total + scenario.tickCount,
            0,
          ),
        ),
      },
    ],
  },
  section: {
    kicker: "Scenario Register",
    title: "Four small cases are enough to show the stack is actually usable.",
    body:
      "Balanced growth, deterministic shortage, wood accumulation, and recovery after worker reallocation all pass through the same engine, artifact contract, and site integration path.",
  },
  labels: {
    config: "Config",
    outcome: "Outcome",
    determinism: "Determinism",
    artifacts: "Artifacts",
    trace: "Tick Trace",
    expected: "Expected",
    status: "Status",
    shortageTicks: "Shortage ticks",
    finalChecksum: "Final checksum",
    replayDigest: "Replay digest",
    fixtureDigest: "Fixture digest",
    snapshotResume: "Resume from snapshot",
    replayVerify: "Replay verify",
    rerun: "Rerun parity",
    fixtureVerify: "Fixture verify",
  },
} as const;

const pageCopy: Record<Locale, typeof sharedCopy> = {
  en: sharedCopy,
  id: sharedCopy,
  ja: sharedCopy,
  zh: sharedCopy,
};

type SimulationPageProps = {
  searchParams?: Promise<SearchParamsLike>;
};

function BoolPill({ value }: { value: boolean }) {
  return (
    <span className={`simulation-pill${value ? " is-pass" : " is-fail"}`}>
      {value ? "pass" : "fail"}
    </span>
  );
}

function ScenarioCard({
  scenario,
  copy,
}: {
  scenario: (typeof settlementDemoCatalog.scenarios)[number];
  copy: (typeof sharedCopy)["labels"];
}) {
  return (
    <article className="panel-card simulation-scenario-card">
      <div className="simulation-card-head">
        <div>
          <p className="gaea-kicker">{scenario.id}</p>
          <h3>{scenario.title}</h3>
        </div>
        <span className="simulation-seed">seed {scenario.seed}</span>
      </div>

      <p className="simulation-card-copy">{scenario.description}</p>

      <div className="simulation-card-strip">
        <div>
          <span>{copy.status}</span>
          <strong>{scenario.runSummary.lastStatus}</strong>
        </div>
        <div>
          <span>Food / Wood</span>
          <strong>
            {scenario.runSummary.finalFood} / {scenario.runSummary.finalWood}
          </strong>
        </div>
        <div>
          <span>{copy.shortageTicks}</span>
          <strong>{scenario.runSummary.shortageTicks}</strong>
        </div>
        <div>
          <span>Ticks</span>
          <strong>{scenario.tickCount}</strong>
        </div>
      </div>

      <div className="simulation-detail-grid">
        <section className="simulation-detail-block">
          <h4>{copy.config}</h4>
          <dl>
            <div>
              <dt>Population</dt>
              <dd>{scenario.config.population}</dd>
            </div>
            <div>
              <dt>Initial inventory</dt>
              <dd>
                food {scenario.config.initialFood}, wood {scenario.config.initialWood}
              </dd>
            </div>
            <div>
              <dt>Initial allocation</dt>
              <dd>
                farmers {scenario.config.initialAllocation.farmers}, loggers{" "}
                {scenario.config.initialAllocation.loggers}
              </dd>
            </div>
            <div>
              <dt>Production</dt>
              <dd>
                +{scenario.config.foodPerFarmer} food / farmer, +
                {scenario.config.woodPerLogger} wood / logger
              </dd>
            </div>
            <div>
              <dt>Consumption</dt>
              <dd>
                {scenario.config.foodConsumptionPerWorker} food / worker,{" "}
                {scenario.config.woodConsumptionPerTick} wood / tick
              </dd>
            </div>
          </dl>
        </section>

        <section className="simulation-detail-block">
          <h4>{copy.outcome}</h4>
          <dl>
            <div>
              <dt>{copy.expected}</dt>
              <dd>
                {scenario.expected.finalStatus}, food {scenario.expected.finalFood}, wood{" "}
                {scenario.expected.finalWood}
              </dd>
            </div>
            <div>
              <dt>Final allocation</dt>
              <dd>
                farmers {scenario.runSummary.finalAllocation.farmers}, loggers{" "}
                {scenario.runSummary.finalAllocation.loggers}, idle{" "}
                {scenario.runSummary.idleWorkers}
              </dd>
            </div>
            <div>
              <dt>Produced totals</dt>
              <dd>
                food {scenario.runSummary.totalFoodProduced}, wood{" "}
                {scenario.runSummary.totalWoodProduced}
              </dd>
            </div>
            <div>
              <dt>Consumed totals</dt>
              <dd>
                food {scenario.runSummary.totalFoodConsumed}, wood{" "}
                {scenario.runSummary.totalWoodConsumed}
              </dd>
            </div>
            <div>
              <dt>Shortage totals</dt>
              <dd>
                food {scenario.runSummary.totalFoodShortage}, wood{" "}
                {scenario.runSummary.totalWoodShortage}
              </dd>
            </div>
            <div>
              <dt>{copy.finalChecksum}</dt>
              <dd>{scenario.runSummary.finalChecksum}</dd>
            </div>
          </dl>
        </section>

        <section className="simulation-detail-block">
          <h4>{copy.determinism}</h4>
          <dl>
            <div>
              <dt>Expectation</dt>
              <dd>
                <BoolPill value={scenario.determinism.expectationPassed} />
              </dd>
            </div>
            <div>
              <dt>{copy.rerun}</dt>
              <dd>
                <BoolPill value={scenario.determinism.rerunParityMatch} />
              </dd>
            </div>
            <div>
              <dt>{copy.replayVerify}</dt>
              <dd>
                <BoolPill value={scenario.determinism.replayVerificationMatch} />
              </dd>
            </div>
            <div>
              <dt>{copy.snapshotResume}</dt>
              <dd>
                <BoolPill value={scenario.determinism.resumeFromSnapshotMatch} />
              </dd>
            </div>
            <div>
              <dt>{copy.fixtureVerify}</dt>
              <dd>
                <BoolPill value={scenario.determinism.fixtureVerificationPassed} />
              </dd>
            </div>
            <div>
              <dt>Resume tick</dt>
              <dd>{scenario.determinism.resumeSnapshotTick ?? "none"}</dd>
            </div>
          </dl>
        </section>

        <section className="simulation-detail-block">
          <h4>{copy.artifacts}</h4>
          <dl>
            <div>
              <dt>Config digest</dt>
              <dd>{scenario.artifactSummary.configDigest}</dd>
            </div>
            <div>
              <dt>{copy.replayDigest}</dt>
              <dd>{scenario.artifactSummary.replayDigest}</dd>
            </div>
            <div>
              <dt>Snapshot digest</dt>
              <dd>{scenario.artifactSummary.snapshotDigest ?? "none"}</dd>
            </div>
            <div>
              <dt>Scenario digest</dt>
              <dd>{scenario.artifactSummary.scenarioDigest ?? "none"}</dd>
            </div>
            <div>
              <dt>{copy.fixtureDigest}</dt>
              <dd>{scenario.artifactDigests.goldenFixture ?? "none"}</dd>
            </div>
            <div>
              <dt>Bundle sizes</dt>
              <dd>
                replay {scenario.artifactSizes.replayArtifact}b, fixture{" "}
                {scenario.artifactSizes.goldenFixture ?? 0}b
              </dd>
            </div>
          </dl>
        </section>
      </div>

      <section className="simulation-trace-block">
        <div className="simulation-trace-head">
          <h4>{copy.trace}</h4>
          <span>
            snapshot cadence {scenario.config.snapshotPolicy} / validation{" "}
            {scenario.config.validationPolicy}
          </span>
        </div>

        <div className="simulation-tick-grid">
          {scenario.tickDigestView.map((tick) => (
            <div key={`${scenario.id}-${tick.tick}`} className="simulation-tick-card">
              <strong>Tick {tick.tick}</strong>
              <span>{tick.checksum}</span>
              <em>{tick.snapshotPresent ? "snapshot captured" : "no snapshot"}</em>
              <p>{tick.phaseOrder.join(" -> ")}</p>
              <small>{tick.validationCheckpoints.join(" / ")}</small>
            </div>
          ))}
        </div>
      </section>
    </article>
  );
}

export default async function SimulationPage({ searchParams }: SimulationPageProps) {
  const locale = getLocaleFromSearchParams(await searchParams);
  const copy = pageCopy[locale];

  return (
    <>
      <GaeaBackground />
      <GaeaSiteHeader locale={locale} />

      <main className="gaea-home gaea-subpage simulation-page">
        <GaeaSubpageManifesto
          locale={locale}
          className="simulation-manifesto"
          kicker={copy.manifesto.kicker}
          title={
            <>
              {copy.manifesto.title.map((line) => (
                <span key={line}>
                  {line}
                  <br />
                </span>
              ))}
            </>
          }
          summary={<p>{copy.manifesto.summary}</p>}
          meta={[...copy.manifesto.meta]}
          actions={[
            {
              label: copy.manifesto.actions.primary,
              href: "/repositories",
            },
            {
              label: copy.manifesto.actions.secondary,
              href: "https://github.com/XENOr-god/xenor-engine",
              external: true,
              variant: "command",
            },
          ]}
          aside={
            <div className="gaea-subpage-aside-panel simulation-manifesto-panel">
              <p className="gaea-subpage-aside-kicker">{copy.manifesto.aside.kicker}</p>
              <div className="gaea-subpage-aside-list">
                {copy.manifesto.aside.rows.map((row) => (
                  <div key={row.id} className="gaea-subpage-aside-row">
                    <span>{row.id}</span>
                    <div>
                      <strong>{row.title}</strong>
                      <p>{row.detail}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          }
        />

        <section className="section compact-top">
          <div className="container">
            <div className="section-head">
              <p className="section-kicker">{copy.summary.kicker}</p>
              <h2>{copy.summary.title}</h2>
              <p>{copy.summary.body}</p>
            </div>

            <div className="simulation-stat-grid">
              {copy.summary.stats.map((stat) => (
                <div key={stat.label} className="panel-card simulation-stat-card">
                  <span>{stat.label}</span>
                  <strong>{stat.value}</strong>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="section">
          <div className="container">
            <div className="section-head">
              <p className="section-kicker">{copy.section.kicker}</p>
              <h2>{copy.section.title}</h2>
              <p>{copy.section.body}</p>
            </div>

            <div className="simulation-scenario-grid">
              {settlementDemoCatalog.scenarios.map((scenario) => (
                <ScenarioCard key={scenario.id} scenario={scenario} copy={copy.labels} />
              ))}
            </div>

            <div className="simulation-route-note">
              <p>
                Generated from the Rust example in `xenor-engine` and committed as a site-facing
                contract.
              </p>
              <LocalizedLink href="/architecture" locale={locale} className="gaea-action">
                Inspect architecture boundaries
              </LocalizedLink>
            </div>
          </div>
        </section>
      </main>

      <GaeaSiteFooter locale={locale} />
    </>
  );
}
