export const XENOR = {
  ticker: '$XNR',
  name: 'XENØr',
  logo: '/assets/images/logo.png',
  tagline: 'Deterministic execution. Verifiable on-chain. Built in Rust.',
  network: 'Solana',

  links: {
    github: 'https://github.com/XENOr-god',
    twitter: 'https://x.com/Xenorlabs',
    x: 'https://x.com/Xenorlabs',
    telegram: 'https://t.me/XenorLabs',
    dex: 'https://dexscreener.com',
    whitepaper: 'https://github.com/XENOr-god/xenor-core',
    docs: 'https://github.com/XENOr-god/xenor-site',
    livesite: 'https://xenor-site.vercel.app',
    phantom: 'https://phantom.app',
    backpack: 'https://backpack.app',
    jupiter: 'https://jup.ag',
  },

  repos: [
    {
      name: 'xenor-core',
      tag: 'Active',
      lang: 'Rust',
      desc: 'Deterministic execution and reward-routing engine',
      url: 'https://github.com/XENOr-god/xenor-core',
    },
    {
      name: 'xenor-sim',
      tag: 'Active',
      lang: 'Rust',
      desc: 'Experiment and simulation runner for protocol behavior',
      url: 'https://github.com/XENOr-god/xenor-sim',
    },
    {
      name: 'xenor-engine',
      tag: 'Active',
      lang: 'Rust',
      desc: 'Canonical deterministic substrate',
      url: 'https://github.com/XENOr-god',
    },
    {
      name: 'xenor-site',
      tag: 'Active',
      lang: 'TypeScript',
      desc: 'Canonical public surface and repository map',
      url: 'https://github.com/XENOr-god/xenor-site',
    },
    {
      name: 'xenor-sale',
      tag: 'Archived',
      lang: 'Archived',
      desc: "Historical sale prototype — research record only",
      url: 'https://github.com/XENOr-god',
    },
  ],

  contract: {
    devWallet: 'URyhfFZLducFix2yroBuwf3jbGtU3BTRSTjgiiDuXNR',
    tokenAddress: null, // null = pending
    verificationStatus: 'pending', // 'pending' | 'deployed' | 'verified'
    chainId: 'solana-mainnet',
  },

  tokenomics: {
    supply: '1,000,000,000',
    teamAlloc: '0%',
    vcSale: '0%',
    fairLaunch: '100%',
  },
};

export const NAVIGATION = [
  { name: 'About', href: '#about' },
  { name: 'Stack', href: '#features' },
  { name: 'Buy', href: '#how-to-buy' },
  { name: 'Token', href: '#tokenomics' },
  { name: 'Verify', href: '#contract' },
  { name: 'Trajectory', href: '#roadmap' },
  { name: 'Safety', href: '#security' },
];

export const FEATURES = [
  {
    id: 'CORE',
    icon: '⚙️',
    label: '∞ CORE',
    title: 'Deterministic Execution',
    description: 'xenor-core is the reward-routing and execution engine in Rust. Same input. Same output. Every time. Zero runtime surprise.'
  },
  {
    id: 'SIM',
    icon: '⟳',
    label: '⟳ SIM',
    title: 'Simulation-Led Validation',
    description: 'xenor-sim runs every scenario before anything ships. Snapshots, replay, fixture checks — the full validation loop.'
  },
  {
    id: 'ENGINE',
    icon: '◎',
    label: '◎ ENGINE',
    title: 'Verifiable Incentive Flow',
    description: 'xenor-engine is the deterministic substrate. The settlement demo on this site is generated by real Rust execution, not invented numbers.'
  },
  {
    id: 'SURFACE',
    icon: '◈',
    label: '◈ SURFACE',
    title: 'Clear Public Surface',
    description: 'xenor-site is the single canonical entry point. Contract address, verification status, architecture, and official links — trust here.'
  }
];

export const HOW_TO_BUY = [
  {
    step: '01',
    title: 'Get a Solana Wallet',
    description: 'Install Phantom or Backpack. Create a new wallet. Write your seed phrase on paper. Not in your phone. Not in a screenshot. On paper.',
    links: [
      { label: 'phantom.app', url: 'https://phantom.app' },
      { label: 'backpack.app', url: 'https://backpack.app' }
    ]
  },
  {
    step: '02',
    title: 'Buy SOL',
    description: "Purchase SOL on Coinbase, Binance, or Kraken. Transfer it to your wallet. Keep a small buffer for network fees — they're nearly nothing on Solana but they exist."
  },
  {
    step: '03',
    title: 'Verify the Contract',
    description: 'Before anything: return to xenor-site. The contract address is valid ONLY when it appears here marked as Verified. Every other source is noise.',
    status: 'warn'
  },
  {
    step: '04',
    title: 'Swap on Jupiter',
    description: "Open jup.ag. Paste the verified contract address. Swap SOL → $XNR. You're now holding deterministic execution infrastructure.",
    links: [{ label: 'jup.ag', url: 'https://jup.ag' }]
  }
];

export const ROADMAP = [
  {
    id: 1,
    phase: 'P-01',
    timeline: 'Q2 2025',
    items: [
      'xenor-core: deterministic execution engine',
      'xenor-sim: simulation and validation layer',
      'xenor-engine: settlement demo + fixture system'
    ]
  },
  {
    id: 2,
    phase: 'P-02',
    timeline: 'Q3 2025',
    items: [
      'xenor-site: canonical public surface live',
      'Contract deployment preparation',
      'Public verification lifecycle active'
    ]
  },
  {
    id: 3,
    phase: 'P-03',
    timeline: 'Q4 2025',
    items: [
      'Token deployment + on-chain verification',
      'xenor-native integration',
      'Expanded simulation surface'
    ]
  }
];



